include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - 'lib/generated/**'
    - 'example/**'
    - 'build/**'
    - '**.g.dart'
    - '**.iconfig.dart'
    - '**.chopper.dart'
    - 'lib/generated_plugin_registrant.dart'
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true
  errors:
    todo: info
    unsafe_html: warning
    avoid_relative_lib_imports: error
    avoid_slow_async_io: error
    avoid_types_as_parameter_names: error
    cancel_subscriptions: error
    close_sinks: error
    valid_regexps: error
    avoid_void_async: error
    no_logic_in_create_state: warning
    missing_required_param: error
# https://dart-lang.github.io/linter/lints/
linter:
  rules:
    #false
    public_member_api_docs: false # Only for package
    avoid_types_on_closure_parameters: false # Not as redundant as helpful and speaking
    omit_local_variable_types: false
    prefer_relative_imports: false
    lines_longer_than_80_chars: false
    curly_braces_in_flow_control_structures: false
    avoid_classes_with_only_static_members: false
    parameter_assignments: false

    # true
    avoid_catching_errors: true
    avoid_catches_without_on_clauses: true
    empty_catches: true
    use_rethrow_when_possible: true
    avoid_returning_null_for_future: true
    valid_regexps: true
    unrelated_type_equality_checks: true
    no_logic_in_create_state: true
    no_duplicate_case_values: true
    unnecessary_lambdas: true
    prefer_if_null_operators: true
    prefer_initializing_formals: true
    type_annotate_public_apis: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    prefer_mixin: true
    unnecessary_const: true
    avoid_shadowing_type_parameters: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    avoid_relative_lib_imports: true
    avoid_print: true
    unsafe_html: true
    avoid_slow_async_io: true
    avoid_types_as_parameter_names: true
    prefer_void_to_null: true
    avoid_empty_else: true
    unnecessary_new: true
    unnecessary_this: true
    prefer_const_declarations: true
    prefer_const_constructors: true
    await_only_futures: true
    avoid_void_async: true
    camel_case_types: true
    cancel_subscriptions: true
    close_sinks: true
    constant_identifier_names: true
    control_flow_in_finally: true
    empty_statements: true
    hash_and_equals: true
    implementation_imports: true
    non_constant_identifier_names: true
    package_api_docs: true
    package_names: true
    package_prefixed_library_names: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_brace_in_string_interps: true
    unnecessary_getters_setters: true
    unnecessary_statements: true
    directives_ordering: true
    always_require_non_null_named_parameters: true
    always_put_required_named_parameters_first: true
