name: bookworm
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_svg: 0.18.1
  auto_size_text: ^2.1.0
  hive: ^1.4.4
  hive_flutter: '>=0.3.1 <2.0.0'
  get:
    git:
      url: https://github.com/jonataslaw/getx.git
      ref: dev
  intl: 0.17.0
  logger: 0.9.2
  retrofit: ^1.3.4
  supercharged: ^1.10.0
  url_launcher: ^5.7.1
  cached_network_image: ^2.3.2+1
  file_picker: ^2.1.4
  flutter_filereader: ^2.2.0
  connectivity_wrapper: ^1.0.4
  pin_code_fields: ^6.0.1
  flutter_cache_manager: ^2.0.0
  path_provider: ^1.6.24
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.10.1
  hive_generator: '>=0.7.1 <2.0.0'
  json_serializable: ^3.5.0
  lint: null
  retrofit_generator: ^1.3.7+6
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
flutter_intl:
  enabled: true
