name: bookworm
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: null
  hive: null
  logger: null
  supercharged: null
  flutter_filereader: null
  flutter_svg: null
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  build_runner:
  hive_generator:
  json_serializable:
  lint:

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/fonts/
flutter_intl:
  enabled: true
